### ISSUE TITLE
Undefined method `each_key` for Sidekiq 6.1.2

### ISSUE THREAD

**Issue by StevenElberger** [iMacTia/sidekiq-logstash#21]
**Sidekiq version:** 6.1.2
**Rails version:** 5.1.7

I tried to use this gem but am seeing the following error after trying to fire off a mailer:
```rb
NoMethodError: undefined method `each_key' for #<String:0x00007ffe96188f48>
Did you mean?  each_byte
from /Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/sidekiq-6.1.2/lib/sidekiq/logger.rb:12:in `ensure in with'
Caused by TypeError: no implicit conversion of String into Hash
from /Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/sidekiq-6.1.2/lib/sidekiq/logger.rb:9:in `merge!'
```

Looks like it's coming from this line in Sidekiq's `logger.rb`:

```rb
module Sidekiq
  module Context
    def self.with(hash)
      current.merge!(hash)
      yield
    ensure
      hash.each_key { |key| current.delete(key) } # error
    end

    def self.current
      Thread.current[:sidekiq_context] ||= {}
    end
  end
  ...
end
```

**Comment by iMacTia** [comment]
Hi @StevenElberger, this is interesting! The `hash` parameter is supposed to be a Hash but apparently you're receiving a String!

Any chance you can see and share more lines of the stacktrace to see how that happened?

**Comment by StevenElberger** [comment]
@iMacTia that's all I could see being printed to STDOUT but I put a debugger on the line above the call to `hash.each_key`.

`hash` evaluates to `"SidekiqUniqueJobs::Client::Middleware DIG-uniquejobs:74cd66879c5f155ba220e358f1dd4388"`

and printing the stack from byebug gives me:

```rb
["(pry):6:in `ensure in with'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/pry_instance.rb:290:in `eval'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/pry_instance.rb:290:in `evaluate_ruby'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/pry_instance.rb:659:in `handle_line'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/pry_instance.rb:261:in `block (2 levels) in eval'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/pry_instance.rb:260:in `catch'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/pry_instance.rb:260:in `block in eval'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/pry_instance.rb:259:in `catch'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/pry_instance.rb:259:in `eval'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/repl.rb:77:in `block in repl'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/repl.rb:67:in `loop'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/repl.rb:67:in `repl'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/repl.rb:38:in `block in start'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/input_lock.rb:78:in `with_ownership'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/repl.rb:38:in `start'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/repl.rb:15:in `start'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/pry_class.rb:191:in `start'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:117:in `block in resume_pry'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:30:in `block (2 levels) in run'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/byebug-11.1.3/lib/byebug/helpers/eval.rb:94:in `allowing_other_threads'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:30:in `block in run'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:29:in `catch'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:29:in `run'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:113:in `resume_pry'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:65:in `at_line'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/byebug-11.1.3/lib/byebug/context.rb:98:in `at_line'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/sidekiq-6.1.2/lib/sidekiq/logger.rb:12:in `ensure in with'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/sidekiq-6.1.2/lib/sidekiq/logger.rb:12:in `with'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/sidekiq-unique-jobs-6.0.23/lib/sidekiq_unique_jobs/sidekiq_unique_jobs.rb:41:in `with_context'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/sidekiq-unique-jobs-6.0.23/lib/sidekiq_unique_jobs/client/middleware.rb:42:in `locked?'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/sidekiq-unique-jobs-6.0.23/lib/sidekiq_unique_jobs/client/middleware.rb:37:in `success?'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/sidekiq-unique-jobs-6.0.23/lib/sidekiq_unique_jobs/client/middleware.rb:27:in `call'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:143:in `invoke'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/sidekiq-6.1.2/lib/sidekiq/client.rb:217:in `process_single'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/sidekiq-6.1.2/lib/sidekiq/client.rb:71:in `push'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/sidekiq-6.1.2/lib/sidekiq/client.rb:137:in `push'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activejob-5.1.7/lib/active_job/queue_adapters/sidekiq_adapter.rb:20:in `enqueue'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activejob-5.1.7/lib/active_job/enqueuing.rb:51:in `block in enqueue'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:108:in `block in run_callbacks'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/newrelic_rpm-6.12.0.367/lib/new_relic/agent/instrumentation/active_job.rb:61:in `block in run_in_trace'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/newrelic_rpm-6.12.0.367/lib/new_relic/agent/method_tracer.rb:75:in `block in trace_execution_scoped'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/newrelic_rpm-6.12.0.367/lib/new_relic/agent/method_tracer_helpers.rb:30:in `block in trace_execution_scoped'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/newrelic_rpm-6.12.0.367/lib/new_relic/agent/tracer.rb:371:in `capture_segment_error'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/newrelic_rpm-6.12.0.367/lib/new_relic/agent/method_tracer_helpers.rb:30:in `trace_execution_scoped'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/newrelic_rpm-6.12.0.367/lib/new_relic/agent/method_tracer.rb:73:in `trace_execution_scoped'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/newrelic_rpm-6.12.0.367/lib/new_relic/agent/instrumentation/active_job.rb:60:in `run_in_trace'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/newrelic_rpm-6.12.0.367/lib/new_relic/agent/instrumentation/active_job.rb:38:in `enqueue'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/newrelic_rpm-6.12.0.367/lib/new_relic/agent/instrumentation/active_job.rb:19:in `block (4 levels) in <top (required)>'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:117:in `instance_exec'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:117:in `block in run_callbacks'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/skylight-core-4.3.1/lib/skylight/core/fanout.rb:25:in `instrument'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/skylight-core-4.3.1/lib/skylight/core/probes/active_job_enqueue.rb:22:in `block in install'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:117:in `instance_exec'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:117:in `block in run_callbacks'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activejob-5.1.7/lib/active_job/logging.rb:15:in `block (3 levels) in <module:Logging>'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activejob-5.1.7/lib/active_job/logging.rb:46:in `tag_logger'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activejob-5.1.7/lib/active_job/logging.rb:14:in `block (2 levels) in <module:Logging>'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:117:in `instance_exec'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:117:in `block in run_callbacks'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:135:in `run_callbacks'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activejob-5.1.7/lib/active_job/enqueuing.rb:47:in `enqueue'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activejob-5.1.7/lib/active_job/configured_job.rb:13:in `perform_later'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/actionmailer-5.1.7/lib/action_mailer/message_delivery.rb:121:in `enqueue_delivery'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/actionmailer-5.1.7/lib/action_mailer/message_delivery.rb:76:in `deliver_later'",
 "(pry):2:in `<main>'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/pry_instance.rb:290:in `eval'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/pry_instance.rb:290:in `evaluate_ruby'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/pry_instance.rb:659:in `handle_line'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/pry_instance.rb:261:in `block (2 levels) in eval'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/pry_instance.rb:260:in `catch'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/pry_instance.rb:260:in `block in eval'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/pry_instance.rb:259:in `catch'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/pry_instance.rb:259:in `eval'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/repl.rb:77:in `block in repl'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/repl.rb:67:in `loop'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/repl.rb:67:in `repl'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/repl.rb:38:in `block in start'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/input_lock.rb:61:in `__with_ownership'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/input_lock.rb:78:in `with_ownership'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/repl.rb:38:in `start'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/repl.rb:15:in `start'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-0.13.0/lib/pry/pry_class.rb:191:in `start'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/pry-byebug-3.9.0/lib/pry-byebug/pry_ext.rb:13:in `start_with_pry_byebug'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/railties-5.1.7/lib/rails/commands/console/console_command.rb:62:in `start'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/railties-5.1.7/lib/rails/commands/console/console_command.rb:17:in `start'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/railties-5.1.7/lib/rails/commands/console/console_command.rb:97:in `perform'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/railties-5.1.7/lib/rails/command/base.rb:63:in `perform'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/railties-5.1.7/lib/rails/command.rb:44:in `invoke'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/railties-5.1.7/lib/rails/commands.rb:16:in `<top (required)>'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/skylight-core-4.3.1/lib/skylight/core/probes.rb:118:in `require'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/skylight-core-4.3.1/lib/skylight/core/probes.rb:118:in `require'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:301:in `block in require'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:267:in `load_dependency'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:301:in `require'",
 "/Users/stevenelberger/Documents/GitHub/my-app/bin/rails:9:in `<top (required)>'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:295:in `load'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:295:in `block in load'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:267:in `load_dependency'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:295:in `load'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/commands/rails.rb:6:in `call'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/command_wrapper.rb:38:in `call'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/application.rb:220:in `block in serve'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/application.rb:180:in `fork'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/application.rb:180:in `serve'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'",
 "/Users/stevenelberger/.rvm/gems/ruby-2.6.5/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'",
 "/Users/stevenelberger/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'",
 "/Users/stevenelberger/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'",
 "-e:1:in `<main>'"]
```

**Comment by iMacTia** [comment]
Thank you @StevenElberger.
I had a quick look at the backtrace and I couldn't find a single reference to this gem. I can see references to Sidekiq, SidekiqUniqueJob and other gems, but not Sidekiq::Logstash unfortunately.

I'm not ruling out it may actually be our fault, but I can't find traces of this gem breaking the logger. Is there any reason why you think it may be this gem?

**Comment by StevenElberger** [comment]
Recently we were able to add this gem successfully without errors so closing this issue 🎉

**Comment by iMacTia** [comment]
Thanks for coming back with the feedback and closing the issue 🙏 !
